{{! Copyright (c) Jupyter Development Team. }}
{{! Distributed under the terms of the Modified BSD License. }}
FROM jupyter/all-spark-notebook:dbb9c7b50531

# Install Kernel Gateway
RUN pip install git+https://github.com/jupyter-incubator/kernel_gateway.git

# Configure container startup
ENTRYPOINT ["tini", "--", "jupyter", "kernelgateway"]

LABEL version="{{appVersion}}"
LABEL service="{{appName}}"

CMD [ \
        "--KernelGatewayApp.api=notebook-http", \
        "--KernelGatewayApp.seed_uri=/srv/notebooks/{{notebookFile}}", \
        "--KernelGatewayApp.allow_origin='http://editor.swagger.io'", \
        " --KernelGatewayApp.allow_methods='GET, POST, PUT, DELETE'", \
        "--KernelGatewayApp.allow_headers='accept, accept-language, content-type'", \
        "--KernelGatewayApp.ip=0.0.0.0" \
    ]

ADD {{notebookFile}} /srv/notebooks/
