# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM node:5

# make the default assume we're in the docker-compose setup where the 
# nginx service is available on the default docker network
ENV GATEWAY_HOST nginx
WORKDIR /src

COPY src/package.json /src/package.json
RUN npm install
COPY src/* /src/

CMD ["node", "client.js"]
